Repository Lukortech-org/React-Typescript, pull requests merged in 2022-10, with the labels that each got.

#10 Update scripts
  .eslintignore
  .eslintrc.js
  .prettierignore
  .prettierrc.js
  package.json
  tsconfig.eslint.json
  tsconfig.json
Labels: 🚧 WiP

#5 Create logo.svg
  logo.svg
Labels: 📐 design

#15 Fixed button behaviour and expanded on the GET api logic
  package-lock.json
  src/components/Navbar/customNavbar.tsx
  src/index.tsx
  src/pages/Table/Table.tsx
  src/server.ts
Labels: ➕ enhancement, ❓ question

#14 Table
  src/App.tsx
  src/components/Layout/layout.css
  src/components/Layout/layout.tsx
  src/components/Navbar/customNavbar.tsx
  src/components/palette.tsx
  src/index.tsx
  src/pages/Auth/Auth.tsx
  src/pages/Home/Home.tsx
  src/pages/Table/Table.tsx
  src/pages/index.ts
  src/server.ts
  src/types/User.ts
Labels: ➕ enhancement, 🔍 review
